# Generated by Django 4.2.5 on 2023-10-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('2', 'Books'), ('6', 'Beauty'), ('4', 'Home'), ('17', 'Automotive'), ('16', 'Pets'), ('14', 'Health'), ('8', 'Jewelry'), ('9', 'Music'), ('10', 'Movies'), ('19', 'Office'), ('18', 'Outdoor'), ('13', 'Furniture'), ('20', 'Gaming'), ('5', 'Sports'), ('1', 'Electronics'), ('12', 'Food'), ('15', 'Tools'), ('3', 'Clothing'), ('11', 'Shoes'), ('7', 'Toys'), ('0', '-null-')], default=0, max_length=10),
        ),
    ]
