# Generated by Django 4.2.5 on 2023-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Beauty', 'Beauty'), ('Home', 'Home'), ('Automotive', 'Automotive'), ('Pets', 'Pets'), ('Health', 'Health'), ('Jewelry', 'Jewelry'), ('Music', 'Music'), ('Movies', 'Movies'), ('Office', 'Office'), ('Outdoor', 'Outdoor'), ('Furniture', 'Furniture'), ('Gaming', 'Gaming'), ('Sports', 'Sports'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Tools', 'Tools'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Toys', 'Toys'), ('null', 'null')], default='null', max_length=15),
        ),
    ]
